// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func layout() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><meta name=\"description\" content=\"Go-Ecommerce\"><meta name=\"htmx-config\" content='{\"allowNestedOobSwaps\":false}'><link href=\"/public/styles.css\" rel=\"stylesheet\"><link rel=\"preconnect\" href=\"https://fonts.googleapis.com\"><link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin><link href=\"https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100..900;1,100..900&display=swap\" rel=\"stylesheet\"><script src=\"/public/htmx.min.js\" defer></script></head><body class=\"bg-grey-100 text-grey-900\" hx-boost=\"true\"><main class=\"flex flex-col gap-8 md:gap-12 lg:gap-16 px-4 pb-24 pt-8 md:px-8\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<footer class=\"flex flex-col gap-4 md:gap-6 lg:gap-8 items-center justify-center bg-grey-200 rounded-2xl p-4 md:p-8 lg:p-12 shadow-lg border border-grey-300\"><p class=\"text-primary-700 border-b-2 border-b-primary-500 py-2 px-4 text-2xl\">E-commerce</p><nav class=\"flex gap-8 md:gap-12 lg:gap-16\"><div class=\"flex flex-col md:flex-row gap-4 md:gap-12 lg:gap-16\"><div class=\"flex flex-col gap-3 md:gap-3 p-2 md:p-3 lg:p-4 border-b border-grey-300 md:border-b-0\"><a href=\"/privacy-policy\" hx-get=\"/privacy-policy\" hx-swap=\"outerHTML\" hx-target=\"#products\" class=\"text-primary-700\">Polityka prywatności</a> <a href=\"/terms\" hx-get=\"/terms\" hx-swap=\"outerHTML\" hx-target=\"#products\" class=\"text-primary-700\">Regulamin</a> <a href=\"/products/1\" hx-get=\"/products/1\" hx-swap=\"outerHTML\" hx-target=\"#products\" class=\"text-primary-700\">Produkty</a></div><div class=\"flex flex-col gap-3 md:gap-4 p-2 md:p-3 lg:p-4\"><a class=\"text-primary-700\" href=\"mailto:example@example.com\">Napisz do nas: <span class=\"ml-1 text-primary-800\">example@example.com</span></a> <a class=\"text-primary-700\" href=\"tel:+48123123123\">Zadzwoń do nas. <span class=\"ml-1 text-primary-800\">+48 123 123 123</span></a></div></div><a class=\"flex gap-2 md:gap-3 items-center md:self-start p-2 md:p-3 lg:p-4\" href=\"/\" hx-get=\"/\" hx-swap=\"outerHTML\" hx-target=\"#products\"><img src=\"/public/icons/logo.svg\" alt=\"logo\" width=\"32px\" height=\"32px\"><p class=\"text-grey-900\">Logo</p></a></nav></footer></main></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
